### ISSUE TITLE
borne des classes

### ISSUE THREAD

**Issue by gilles13** [julienjamme/utilitr-carto#1]
voir https://www.insee.fr/fr/statistiques/5371235?sommaire=5371304#graphique-figure2

**Comment by gilles13** [comment]
![tauxpauvreteggplot](https://user-images.githubusercontent.com/5504151/150686981-3ebbb867-e1d2-4165-963b-dd94c52c3690.png)

**Comment by julienjamme** [comment]
Peut-être un problème d’arrondis entre les données utilisées par l’auteur et les tiennes.
Le 17 que tu utilises est peut-être un 16.95 que l’auteur a utilisé.
Sinon très bien ta carte.
